feat: add Transaction Date
SalesVista/strings pull request #17
Opened 2024-01-17 21:00 UTC by nnsier

2024-01-17 22:03 UTC, nexdrew requested changes
See comments, particularly the first two.

2024-01-17 22:03 UTC, nexdrew commented on src/index.js
> +  [Strings.TRANSACTION_DATE]: 'Transaction Date',
Think we should do anything special for the default abbreviation of this, or do you think `'TD'`/`'td'` is fine?

Was wondering if something like `'TrxDt'` or `'trx'` would be better. Ideally would use a pattern that works for "Effective Date"  too (e.g. `'EffDt'` or `'eff'`), but it's probably not worth the effort of coding a special case here. Just interested in others' thoughts.

2024-01-19 20:09 UTC, nexdrew commented on src/index.js
> +  [Strings.TRANSACTION_DATE]: 'Transaction Date',
Added in commit 2d9e94701b6b3fa5dbe6f248ccfecd654659143d

2024-01-19 20:09 UTC, nexdrew commented on src/index.js
> +  [Strings.TRANSACTION_DATE]: 'Transaction Date',
Ignoring this for now.

2024-01-19 20:09 UTC, nexdrew approved these changes

2024-01-19 20:47 UTC, nnsier commented
I am not an authorized user so I cannot merge :(

2024-01-19 22:29 UTC, merged